version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: rks007/wanderlust_be:latest
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: rks007/wanderlust_fe:latest
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb

volumes:
  data:
